### ISSUE TITLE
Automatically update unread messages count

### ISSUE THREAD

**Issue by microcluster** [alepez/devand#120]
**Describe the bug**
Message notifications number doesn't appear on real-time

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04.1 LTS x86_64]
 - Browser [chrome]
 - Version [84.0.4147.125]

**Comment by alepez** [comment]
When there are new incoming messages, the counter (see image below) should be updated automatically. Now, if user A receive a message and has already the website opened, user A has to reload the page to see the counter updated.

![image](https://user-images.githubusercontent.com/877244/91022696-ddd9ad00-e5f5-11ea-9824-fdf6aa9c0886.png)

This require #49 or at least some kind of polling (like is now implemented the CodeNow feature).

**Comment by alepez** [comment]
See also #77
