### ISSUE TITLE
Improve affinity representation in Schedule section

### ISSUE THREAD

**Issue by guerinoni** [alepez/devand#42]
In the "Schedule" section is not very clear what for example "0%" means

Screenshot from my profile

![image](https://user-images.githubusercontent.com/41150432/87786663-a2033900-c83a-11ea-9bb9-8d65a97bb4fa.png)

**Comment by alepez** [comment]
See https://github.com/alepez/devand/issues/43

**Comment by alepez** [comment]
See https://github.com/alepez/devand/issues/44

**Comment by alepez** [comment]
We have actually two different problems here:

 - 0% (or any % next to other users name) is the affinity with that user, but you cannot know from this page
 - having 0% affinity users shown here does not make any sense #43 

We should make more clear what those numbers are, what affinity is and why you cannot see any user with more then 0% affinity (you haven't selected any language). See #44

**Comment by alepez** [comment]
And we have another problem here: users are not sorted by affinity.

![image](https://user-images.githubusercontent.com/877244/87828526-66d62980-c87d-11ea-9819-1fdcb47a4be0.png)
