### ISSUE TITLE
Remove delay of 1 week in when schedule session

### ISSUE THREAD

**Issue by guerinoni** [alepez/devand#79]
I know this is not a bug but seems a bug! Maybe is more useful to show a list of available starting from next day and not delayed of a week

**Comment by alepez** [comment]
The idea was that users should have some day (a week) to organize the p-p session. But I agree on the fact that it seems weird. And if user A is able to organize with B for a session on the same day, who are we to not let them?

So, do you are free to create PR (or to organize with me for a p-p session)
