### ISSUE TITLE
Improper tab behavior on the login page

### ISSUE THREAD

**Issue by vishalsodani** [alepez/devand#98]
**Describe the bug**
On hitting tab the flow should be from username field to the password field and then to the sign in button. But, the 'forgot password' link gets the focus after hitting the tab from the username textbox. 

**Expected behavior**
We should have autofocus on the username textbox. And also proper tabindex.

**Comment by alepez** [comment]
You're right. I also use tab to move between inputs and I find it frustrating.

Adding a `tabindex` attribute should be enough. https://stackoverflow.com/questions/13435217/skip-input-when-press-tab

**Comment by alepez** [comment]
Just tried with chrom devtools. Adding `tabindex="-1"` on the "Forgot password" anchor does the trick.

**Comment by vishalsodani** [comment]
> Just tried with chrome devtools. Adding `tabindex="-1"` on the "Forgot password" anchor does the trick.

ok. But I added tabindex to the 3 html elements.

**Comment by alepez** [comment]
No problem, I wrote it before your PR
