### ISSUE TITLE
Website crashes chromebooks.

### ISSUE THREAD

**Issue by ergpopler** [alepez/devand#99]
When I go on the website from my chromebook, at first it works fine, then after ~15 seconds it starts slowing down, then after around ~30 seconds my mouse starts glitching everywhere and after about ~40 seconds my mouse freezes, then after about ~45 seconds all functionality stops, I've tried on both of my chromebooks, which are fully up to date, and i sent the link to my cousin who has a pretty beefy chromebook, and it did the same thing to his too, just wanted to tell you.

despite the issues it causes, no functionality is lost, it looks the same as on my main PC using firefox.

**Comment by alepez** [comment]
I'm sorry, but I don't have any chromebook to test. Does it happen only in a specific page? Can you see if there's something strange in the browser log?

**Comment by alepez** [comment]
@ergpopler can you help me on this bug? I don't have any chromebook to test and it appears to happen only in this specific platform.

**Comment by ergpopler** [comment]
I have found it to be a bad interaction between the website and a plugin i installed, not devand's fault :) sorry

**Comment by alepez** [comment]
Thanks @ergpopler to le me know.
